# -*- coding: utf-8 -*-
"""18It035_DS_pr1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10pW0AW2cxPOLSm4Ec664ot1U7L1T7sT9
"""

from bs4 import BeautifulSoup
import requests
import csv
import pandas as pd

source = requests.get('https://www.flipkart.com/search?q=t+shirts&as=on&as-show=on&otracker=AS_Query_TrendingAutoSuggest_3_0_na_na_na&otracker1=AS_Query_TrendingAutoSuggest_3_0_na_na_na&as-pos=3&as-type=TRENDING&suggestionId=t+shirts&requestId=3080d4af-a665-4763-a871-5d8751a88c37&as-backfill=on').text
soup = BeautifulSoup(source,'html')

name = []
price = []
string = ""

for i in soup.find_all('a', class_='IRpwTa'):
  string = i.text
  name.append(string.strip())

for i in soup.find_all('div',class_='_30jeq3'):
  price.append(i.text)

print(len(name))
print(len(price))

df = pd.DataFrame({'Product Name':name, 'Price':price})
df.to_csv('data.csv', index=False ,encoding='utf-8')